name: pynever
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - onnx
      - torch
      - torchvision
      - ortools
      - pysmt
      - multipledispatch