name: NeVer2
ami: ami-0aff18ec83b712f05
scripts_dir: vnncomp_scripts
manual_installation_step: True
run_installation_script_as_root: True
run_post_installation_script_as_root: False
run_toolkit_as_root: False
description: >
  NeVer2 is a neural network verifier developed at University of Genova that enables design, learning and verification 
  of feed-forward neural networks with Fully Connected, Convolutional and ReLU layers
